/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'AtYourService',
    description: 'Generated by Simon',
}

export default function VenueLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <main className="flex min-h-screen w-full">
                    <aside id="logo-sidebar" className="h-screen w-2/12" aria-label="Sidebar">
                        <div className="h-full px-3 py-4 overflow-y-auto bg-gray-800">
                            <a href="https://beatvenues.be/" className="flex items-center pl-2.5 mb-5">
                                <img src="https://beatvenues.be/wp-content/uploads/2022/02/be-at-logo.png" className="h-6 mr-3 sm:h-7" alt="be-at Logo" />
                            </a>
                            <hr className="h-px bg-gray-200 border-0 dark:bg-gray-700"></hr>
                            <ul className="space-y-2 font-medium">
                                <li>
                                    <Link href="/" className="flex items-center p-2 rounded-lg text-white hover:bg-gray-700 group">
                                        <span className="ml-3">Dashboard</span>
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/organisations" className="flex items-center p-2  rounded-lg text-white hover:bg-gray-700 group">
                                        <span className="flex-1 ml-3 whitespace-nowrap">Organisations</span>
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/events" className="flex items-center p-2  rounded-lg text-white hover:bg-gray-700 group">
                                        <span className="flex-1 ml-3 whitespace-nowrap">Events</span>
                                    </Link>
                                </li>
                                <li>
                                    <Link href="venues" className="flex items-center p-2  rounded-lg text-white bg-gray-700 group">
                                        <span className="flex-1 ml-3 whitespace-nowrap">Venues</span>
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/admin" className="flex items-center p-2  rounded-lg text-white hover:bg-gray-700 group">
                                        <span className="flex-1 ml-3 whitespace-nowrap">Admin</span>
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </aside>
                    <div className="p-4 w-10/12">{children}</div>
                </main>
            </body>
        </html>
    )
}
